name: Upstash Keep Alive

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号运行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  ping-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Send Keep-alive Command
        run: |
          curl "${{ secrets.UPSTASH_REDIS_REST_URL }}/get/keepalive" \
          -H "Authorization: Bearer ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}"
